# Generated by Django 2.2 on 2019-04-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menusections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusections',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='menusections',
            name='date_modified',
        ),
    ]
